# Generated by Django 4.2.4 on 2023-11-26 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('addition', models.FileField(null=True, upload_to='', verbose_name='Материалы')),
                ('identifier', models.IntegerField(default=tasks.utils.generate_identifier, verbose_name='Идентификатор')),
                ('upload', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('feedback', models.BooleanField(null=True, verbose_name='Показывать результат')),
                ('attempts', models.IntegerField(default=1, null=True, verbose_name='Количество попыток')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('creator', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('test_type', models.BooleanField(verbose_name='Тестовый')),
                ('variants', models.JSONField(default=None, null=True, verbose_name='Варианты')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('task', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=None, null=True, verbose_name='Ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('user', 'task'),
            },
        ),
    ]
